name: Pre Publish
on:
  push:
    branches:
      - master

jobs:
  pre-publish:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set timezone to Asia/Shanghai
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Echo current time
        run: timedatectl

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install pnpm
        run: |
          npm install -g pnpm
          # pnpm config set store-dir $(pwd)/.pnpm-store
          # pnpm config set recursive-optional true

      - name: Install Dependence
        run: pnpm install --no-frozen-lockfile

      - name: Build dist
        run: |
          git pull -p
          pnpm run build

      - name: Pre publish
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            update:
              - 'src/**'
              - README.md
              - package.json
              - rollup.config.js
              - tsconfig.json
              - .babelrc
              - .github/workflows/publish.yml

      - name: Repository Dispatch
        if: steps.changes.outputs.update == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN }}
          # 也可以直接写成R： GITHUB_REPOSITORY
          # https://docs.github.com/zh/actions/learn-github-actions/variables
          repository: ${{ github.repository }}
          event-type: to-publish-npm
